/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// CreateEmailCustomizationRequest
    /// </summary>
    [DataContract(Name = "CreateEmailCustomizationRequest")]
    public partial class CreateEmailCustomizationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEmailCustomizationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateEmailCustomizationRequest()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEmailCustomizationRequest" /> class.
        /// </summary>
        /// <param name="templateProperties">Email customization configuration as key value pair (required).</param>
        /// <param name="orgIdentifier">Unique ID or name of org    Version: 10.12.0.cl or later .</param>
        public CreateEmailCustomizationRequest(TemplatePropertiesInputCreate templateProperties = default, string orgIdentifier = default)
        {
            // to ensure "templateProperties" is required (not null)
            if (templateProperties == null)
            {
                throw new ArgumentNullException("templateProperties is a required property for CreateEmailCustomizationRequest and cannot be null");
            }
            this.TemplateProperties = templateProperties;
            this.OrgIdentifier = orgIdentifier;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Email customization configuration as key value pair
        /// </summary>
        /// <value>Email customization configuration as key value pair</value>
        [DataMember(Name = "template_properties", IsRequired = true, EmitDefaultValue = true)]
        public TemplatePropertiesInputCreate TemplateProperties { get; set; }

        /// <summary>
        /// Unique ID or name of org    Version: 10.12.0.cl or later 
        /// </summary>
        /// <value>Unique ID or name of org    Version: 10.12.0.cl or later </value>
        [DataMember(Name = "org_identifier", EmitDefaultValue = false)]
        public string OrgIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateEmailCustomizationRequest {\n");
            sb.Append("  TemplateProperties: ").Append(TemplateProperties).Append("\n");
            sb.Append("  OrgIdentifier: ").Append(OrgIdentifier).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
