/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// Detail for a single feature. Fields are populated according to the scope of the search: cluster-admin (CLUSTER) responses populate assigned_orgs, is_org_aware, and (for non-org-aware features) feature_value; org-admin (ORG) responses populate element_type, element_config, and element_value.
    /// </summary>
    [DataContract(Name = "FeatureDetail")]
    public partial class FeatureDetail : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureDetail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeatureDetail()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureDetail" /> class.
        /// </summary>
        /// <param name="featureId">Underlying unique feature ID. (required).</param>
        /// <param name="featureName">User-friendly feature name. Present when the feature declares one..</param>
        /// <param name="assignedOrgs">Orgs currently assigned to this feature. Populated in the cluster-admin view..</param>
        /// <param name="isOrgAware">Whether the feature is Org-aware. Org-aware features are managed via per-Org assignment; non-org-aware features are cluster-level toggles. Populated in the cluster-admin view..</param>
        /// <param name="featureValue">Current cluster-level value of the feature. Populated in the cluster-admin view for non-org-aware features; null for Org-aware features..</param>
        /// <param name="elementType">UI element type hint for the feature. Populated in the org-admin view..</param>
        /// <param name="elementConfig">UI element configuration for the feature. Populated in the org-admin view..</param>
        /// <param name="elementValue">Current value of the feature for the requested Org. Populated in the org-admin view..</param>
        /// <param name="docsUrl">Per-feature documentation URL, when available..</param>
        public FeatureDetail(string featureId = default, string featureName = default, List<FeatureOrgInfo> assignedOrgs = default, bool? isOrgAware = default, string featureValue = default, string elementType = default, Object elementConfig = default, string elementValue = default, string docsUrl = default)
        {
            // to ensure "featureId" is required (not null)
            if (featureId == null)
            {
                throw new ArgumentNullException("featureId is a required property for FeatureDetail and cannot be null");
            }
            this.FeatureId = featureId;
            this.FeatureName = featureName;
            this.AssignedOrgs = assignedOrgs;
            this.IsOrgAware = isOrgAware;
            this.FeatureValue = featureValue;
            this.ElementType = elementType;
            this.ElementConfig = elementConfig;
            this.ElementValue = elementValue;
            this.DocsUrl = docsUrl;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Underlying unique feature ID.
        /// </summary>
        /// <value>Underlying unique feature ID.</value>
        [DataMember(Name = "feature_id", IsRequired = true, EmitDefaultValue = true)]
        public string FeatureId { get; set; }

        /// <summary>
        /// User-friendly feature name. Present when the feature declares one.
        /// </summary>
        /// <value>User-friendly feature name. Present when the feature declares one.</value>
        [DataMember(Name = "feature_name", EmitDefaultValue = true)]
        public string FeatureName { get; set; }

        /// <summary>
        /// Orgs currently assigned to this feature. Populated in the cluster-admin view.
        /// </summary>
        /// <value>Orgs currently assigned to this feature. Populated in the cluster-admin view.</value>
        [DataMember(Name = "assigned_orgs", EmitDefaultValue = true)]
        public List<FeatureOrgInfo> AssignedOrgs { get; set; }

        /// <summary>
        /// Whether the feature is Org-aware. Org-aware features are managed via per-Org assignment; non-org-aware features are cluster-level toggles. Populated in the cluster-admin view.
        /// </summary>
        /// <value>Whether the feature is Org-aware. Org-aware features are managed via per-Org assignment; non-org-aware features are cluster-level toggles. Populated in the cluster-admin view.</value>
        [DataMember(Name = "is_org_aware", EmitDefaultValue = true)]
        public bool? IsOrgAware { get; set; }

        /// <summary>
        /// Current cluster-level value of the feature. Populated in the cluster-admin view for non-org-aware features; null for Org-aware features.
        /// </summary>
        /// <value>Current cluster-level value of the feature. Populated in the cluster-admin view for non-org-aware features; null for Org-aware features.</value>
        [DataMember(Name = "feature_value", EmitDefaultValue = true)]
        public string FeatureValue { get; set; }

        /// <summary>
        /// UI element type hint for the feature. Populated in the org-admin view.
        /// </summary>
        /// <value>UI element type hint for the feature. Populated in the org-admin view.</value>
        [DataMember(Name = "element_type", EmitDefaultValue = true)]
        public string ElementType { get; set; }

        /// <summary>
        /// UI element configuration for the feature. Populated in the org-admin view.
        /// </summary>
        /// <value>UI element configuration for the feature. Populated in the org-admin view.</value>
        [DataMember(Name = "element_config", EmitDefaultValue = true)]
        public Object ElementConfig { get; set; }

        /// <summary>
        /// Current value of the feature for the requested Org. Populated in the org-admin view.
        /// </summary>
        /// <value>Current value of the feature for the requested Org. Populated in the org-admin view.</value>
        [DataMember(Name = "element_value", EmitDefaultValue = true)]
        public string ElementValue { get; set; }

        /// <summary>
        /// Per-feature documentation URL, when available.
        /// </summary>
        /// <value>Per-feature documentation URL, when available.</value>
        [DataMember(Name = "docs_url", EmitDefaultValue = true)]
        public string DocsUrl { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeatureDetail {\n");
            sb.Append("  FeatureId: ").Append(FeatureId).Append("\n");
            sb.Append("  FeatureName: ").Append(FeatureName).Append("\n");
            sb.Append("  AssignedOrgs: ").Append(AssignedOrgs).Append("\n");
            sb.Append("  IsOrgAware: ").Append(IsOrgAware).Append("\n");
            sb.Append("  FeatureValue: ").Append(FeatureValue).Append("\n");
            sb.Append("  ElementType: ").Append(ElementType).Append("\n");
            sb.Append("  ElementConfig: ").Append(ElementConfig).Append("\n");
            sb.Append("  ElementValue: ").Append(ElementValue).Append("\n");
            sb.Append("  DocsUrl: ").Append(DocsUrl).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
