/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// One per-item import failure surfaced by importMemory. &#x60;line_number&#x60; is the best-effort line number in the uploaded YAML; &#x60;field_name&#x60; is a dotted path within the item (e.g. &#x60;content.rule_definition&#x60;) for inline highlighting; absent when the failure is item-level rather than field-level.
    /// </summary>
    [DataContract(Name = "ImportFailure")]
    public partial class ImportFailure : IValidatableObject
    {
        /// <summary>
        /// Machine-readable category for the failure (e.g. &#x60;VALIDATION&#x60;, &#x60;ACCESS_DENIED&#x60;, &#x60;CHAR_LIMIT&#x60;).
        /// </summary>
        /// <value>Machine-readable category for the failure (e.g. &#x60;VALIDATION&#x60;, &#x60;ACCESS_DENIED&#x60;, &#x60;CHAR_LIMIT&#x60;).</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum UNKNOWNFAILUREREASON for value: UNKNOWN_FAILURE_REASON
            /// </summary>
            [EnumMember(Value = "UNKNOWN_FAILURE_REASON")]
            UNKNOWNFAILUREREASON = 1,

            /// <summary>
            /// Enum VALIDATION for value: VALIDATION
            /// </summary>
            [EnumMember(Value = "VALIDATION")]
            VALIDATION = 2,

            /// <summary>
            /// Enum UNRESOLVEDSOURCE for value: UNRESOLVED_SOURCE
            /// </summary>
            [EnumMember(Value = "UNRESOLVED_SOURCE")]
            UNRESOLVEDSOURCE = 3,

            /// <summary>
            /// Enum ACCESSDENIED for value: ACCESS_DENIED
            /// </summary>
            [EnumMember(Value = "ACCESS_DENIED")]
            ACCESSDENIED = 4,

            /// <summary>
            /// Enum CHARLIMIT for value: CHAR_LIMIT
            /// </summary>
            [EnumMember(Value = "CHAR_LIMIT")]
            CHARLIMIT = 5,

            /// <summary>
            /// Enum SCHEMA for value: SCHEMA
            /// </summary>
            [EnumMember(Value = "SCHEMA")]
            SCHEMA = 6
        }


        /// <summary>
        /// Machine-readable category for the failure (e.g. &#x60;VALIDATION&#x60;, &#x60;ACCESS_DENIED&#x60;, &#x60;CHAR_LIMIT&#x60;).
        /// </summary>
        /// <value>Machine-readable category for the failure (e.g. &#x60;VALIDATION&#x60;, &#x60;ACCESS_DENIED&#x60;, &#x60;CHAR_LIMIT&#x60;).</value>
        [DataMember(Name = "reason", EmitDefaultValue = true)]
        public ReasonEnum? Reason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportFailure" /> class.
        /// </summary>
        /// <param name="lineNumber">Best-effort line number of the offending item in the uploaded YAML. May be null when the line cannot be determined..</param>
        /// <param name="reason">Machine-readable category for the failure (e.g. &#x60;VALIDATION&#x60;, &#x60;ACCESS_DENIED&#x60;, &#x60;CHAR_LIMIT&#x60;)..</param>
        /// <param name="fieldName">Dotted path to the offending field within the item (e.g. &#x60;content.rule_definition&#x60;) for inline highlighting. Absent when the failure is item-level rather than field-level..</param>
        /// <param name="message">Human-readable description of the failure..</param>
        public ImportFailure(int? lineNumber = default, ReasonEnum? reason = default, string fieldName = default, string message = default)
        {
            this.LineNumber = lineNumber;
            this.Reason = reason;
            this.FieldName = fieldName;
            this.Message = message;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Best-effort line number of the offending item in the uploaded YAML. May be null when the line cannot be determined.
        /// </summary>
        /// <value>Best-effort line number of the offending item in the uploaded YAML. May be null when the line cannot be determined.</value>
        [DataMember(Name = "line_number", EmitDefaultValue = true)]
        public int? LineNumber { get; set; }

        /// <summary>
        /// Dotted path to the offending field within the item (e.g. &#x60;content.rule_definition&#x60;) for inline highlighting. Absent when the failure is item-level rather than field-level.
        /// </summary>
        /// <value>Dotted path to the offending field within the item (e.g. &#x60;content.rule_definition&#x60;) for inline highlighting. Absent when the failure is item-level rather than field-level.</value>
        [DataMember(Name = "field_name", EmitDefaultValue = true)]
        public string FieldName { get; set; }

        /// <summary>
        /// Human-readable description of the failure.
        /// </summary>
        /// <value>Human-readable description of the failure.</value>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportFailure {\n");
            sb.Append("  LineNumber: ").Append(LineNumber).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  FieldName: ").Append(FieldName).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
