/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// Per (memory type, target source) summary of what importMemory did — or would do, in DRY_RUN. &#x60;deleted_record_count&#x60; and &#x60;inserted_record_count&#x60; are previews in DRY_RUN and actuals in EXECUTE_IMPORT.
    /// </summary>
    [DataContract(Name = "ImportSummary")]
    public partial class ImportSummary : IValidatableObject
    {
        /// <summary>
        /// The kind of memory (&#x60;RULES&#x60;, &#x60;RECIPES&#x60;, or &#x60;ALWAYS_APPLY_RULES&#x60;) these counts apply to.
        /// </summary>
        /// <value>The kind of memory (&#x60;RULES&#x60;, &#x60;RECIPES&#x60;, or &#x60;ALWAYS_APPLY_RULES&#x60;) these counts apply to.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MemoryTypeEnum
        {
            /// <summary>
            /// Enum RULES for value: RULES
            /// </summary>
            [EnumMember(Value = "RULES")]
            RULES = 1,

            /// <summary>
            /// Enum RECIPES for value: RECIPES
            /// </summary>
            [EnumMember(Value = "RECIPES")]
            RECIPES = 2,

            /// <summary>
            /// Enum ALWAYSAPPLYRULES for value: ALWAYS_APPLY_RULES
            /// </summary>
            [EnumMember(Value = "ALWAYS_APPLY_RULES")]
            ALWAYSAPPLYRULES = 3
        }


        /// <summary>
        /// The kind of memory (&#x60;RULES&#x60;, &#x60;RECIPES&#x60;, or &#x60;ALWAYS_APPLY_RULES&#x60;) these counts apply to.
        /// </summary>
        /// <value>The kind of memory (&#x60;RULES&#x60;, &#x60;RECIPES&#x60;, or &#x60;ALWAYS_APPLY_RULES&#x60;) these counts apply to.</value>
        [DataMember(Name = "memory_type", EmitDefaultValue = true)]
        public MemoryTypeEnum? MemoryType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportSummary" /> class.
        /// </summary>
        /// <param name="memoryType">The kind of memory (&#x60;RULES&#x60;, &#x60;RECIPES&#x60;, or &#x60;ALWAYS_APPLY_RULES&#x60;) these counts apply to..</param>
        /// <param name="source">source.</param>
        /// <param name="existingRecordCount">Number of memory entries of this type that already existed on the target object before the import..</param>
        /// <param name="deletedRecordCount">Number of existing entries that will be (DRY_RUN) or were (EXECUTE_IMPORT) deleted as part of the replacement..</param>
        /// <param name="insertedRecordCount">Number of entries from the payload that will be (DRY_RUN) or were (EXECUTE_IMPORT) inserted..</param>
        /// <param name="failedRecordCount">Number of records of this type that failed validation or processing..</param>
        public ImportSummary(MemoryTypeEnum? memoryType = default, ImportTargetSource source = default, int? existingRecordCount = default, int? deletedRecordCount = default, int? insertedRecordCount = default, int? failedRecordCount = default)
        {
            this.MemoryType = memoryType;
            this.Source = source;
            this.ExistingRecordCount = existingRecordCount;
            this.DeletedRecordCount = deletedRecordCount;
            this.InsertedRecordCount = insertedRecordCount;
            this.FailedRecordCount = failedRecordCount;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name = "source", EmitDefaultValue = false)]
        public ImportTargetSource Source { get; set; }

        /// <summary>
        /// Number of memory entries of this type that already existed on the target object before the import.
        /// </summary>
        /// <value>Number of memory entries of this type that already existed on the target object before the import.</value>
        [DataMember(Name = "existing_record_count", EmitDefaultValue = true)]
        public int? ExistingRecordCount { get; set; }

        /// <summary>
        /// Number of existing entries that will be (DRY_RUN) or were (EXECUTE_IMPORT) deleted as part of the replacement.
        /// </summary>
        /// <value>Number of existing entries that will be (DRY_RUN) or were (EXECUTE_IMPORT) deleted as part of the replacement.</value>
        [DataMember(Name = "deleted_record_count", EmitDefaultValue = true)]
        public int? DeletedRecordCount { get; set; }

        /// <summary>
        /// Number of entries from the payload that will be (DRY_RUN) or were (EXECUTE_IMPORT) inserted.
        /// </summary>
        /// <value>Number of entries from the payload that will be (DRY_RUN) or were (EXECUTE_IMPORT) inserted.</value>
        [DataMember(Name = "inserted_record_count", EmitDefaultValue = true)]
        public int? InsertedRecordCount { get; set; }

        /// <summary>
        /// Number of records of this type that failed validation or processing.
        /// </summary>
        /// <value>Number of records of this type that failed validation or processing.</value>
        [DataMember(Name = "failed_record_count", EmitDefaultValue = true)]
        public int? FailedRecordCount { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportSummary {\n");
            sb.Append("  MemoryType: ").Append(MemoryType).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  ExistingRecordCount: ").Append(ExistingRecordCount).Append("\n");
            sb.Append("  DeletedRecordCount: ").Append(DeletedRecordCount).Append("\n");
            sb.Append("  InsertedRecordCount: ").Append(InsertedRecordCount).Append("\n");
            sb.Append("  FailedRecordCount: ").Append(FailedRecordCount).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
