/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// Result of a dataset discovery step.
    /// </summary>
    [DataContract(Name = "SearchDatasetsResponseItem")]
    public partial class SearchDatasetsResponseItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDatasetsResponseItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchDatasetsResponseItem()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDatasetsResponseItem" /> class.
        /// </summary>
        /// <param name="type">Variant discriminator. Always &#x60;\&quot;search_datasets\&quot;&#x60;. (required).</param>
        /// <param name="timestampInMillis">Milliseconds since Unix epoch when this item was produced. (required).</param>
        /// <param name="isThinking">True when the item represents internal agent reasoning rather than user-facing output..</param>
        /// <param name="stepTitle">Human-readable label for the agent step producing this item..</param>
        /// <param name="text">Summary message describing the dataset search results. (required).</param>
        /// <param name="dataSources">Dataset descriptors returned by the &#x60;search_datasets&#x60; tool..</param>
        public SearchDatasetsResponseItem(string type = default, Object timestampInMillis = default, bool? isThinking = default, string stepTitle = default, string text = default, List<DataSourceInfo> dataSources = default)
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for SearchDatasetsResponseItem and cannot be null");
            }
            this.Type = type;
            // to ensure "timestampInMillis" is required (not null)
            if (timestampInMillis == null)
            {
                throw new ArgumentNullException("timestampInMillis is a required property for SearchDatasetsResponseItem and cannot be null");
            }
            this.TimestampInMillis = timestampInMillis;
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for SearchDatasetsResponseItem and cannot be null");
            }
            this.Text = text;
            this.IsThinking = isThinking;
            this.StepTitle = stepTitle;
            this.DataSources = dataSources;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Variant discriminator. Always &#x60;\&quot;search_datasets\&quot;&#x60;.
        /// </summary>
        /// <value>Variant discriminator. Always &#x60;\&quot;search_datasets\&quot;&#x60;.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Milliseconds since Unix epoch when this item was produced.
        /// </summary>
        /// <value>Milliseconds since Unix epoch when this item was produced.</value>
        [DataMember(Name = "timestamp_in_millis", IsRequired = true, EmitDefaultValue = true)]
        public Object TimestampInMillis { get; set; }

        /// <summary>
        /// True when the item represents internal agent reasoning rather than user-facing output.
        /// </summary>
        /// <value>True when the item represents internal agent reasoning rather than user-facing output.</value>
        [DataMember(Name = "is_thinking", EmitDefaultValue = true)]
        public bool? IsThinking { get; set; }

        /// <summary>
        /// Human-readable label for the agent step producing this item.
        /// </summary>
        /// <value>Human-readable label for the agent step producing this item.</value>
        [DataMember(Name = "step_title", EmitDefaultValue = true)]
        public string StepTitle { get; set; }

        /// <summary>
        /// Summary message describing the dataset search results.
        /// </summary>
        /// <value>Summary message describing the dataset search results.</value>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Dataset descriptors returned by the &#x60;search_datasets&#x60; tool.
        /// </summary>
        /// <value>Dataset descriptors returned by the &#x60;search_datasets&#x60; tool.</value>
        [DataMember(Name = "data_sources", EmitDefaultValue = true)]
        public List<DataSourceInfo> DataSources { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchDatasetsResponseItem {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TimestampInMillis: ").Append(TimestampInMillis).Append("\n");
            sb.Append("  IsThinking: ").Append(IsThinking).Append("\n");
            sb.Append("  StepTitle: ").Append(StepTitle).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  DataSources: ").Append(DataSources).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
