/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// Response from sync metadata operation.
    /// </summary>
    [DataContract(Name = "SyncMetadataResponse")]
    public partial class SyncMetadataResponse : IValidatableObject
    {
        /// <summary>
        /// Overall status of the sync operation.
        /// </summary>
        /// <value>Overall status of the sync operation.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum SUCCESS for value: SUCCESS
            /// </summary>
            [EnumMember(Value = "SUCCESS")]
            SUCCESS = 1,

            /// <summary>
            /// Enum PARTIALSUCCESS for value: PARTIAL_SUCCESS
            /// </summary>
            [EnumMember(Value = "PARTIAL_SUCCESS")]
            PARTIALSUCCESS = 2,

            /// <summary>
            /// Enum NOUPDATE for value: NO_UPDATE
            /// </summary>
            [EnumMember(Value = "NO_UPDATE")]
            NOUPDATE = 3
        }


        /// <summary>
        /// Overall status of the sync operation.
        /// </summary>
        /// <value>Overall status of the sync operation.</value>
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncMetadataResponse" /> class.
        /// </summary>
        /// <param name="status">Overall status of the sync operation..</param>
        /// <param name="tablesUpdated">Number of tables with metadata updates..</param>
        /// <param name="columnsUpdated">Number of columns with metadata updates..</param>
        /// <param name="tablesFailed">Number of tables that failed to sync (for PARTIAL_SUCCESS)..</param>
        /// <param name="columnsFailed">Number of columns that failed to sync (for PARTIAL_SUCCESS)..</param>
        /// <param name="message">Message describing the result..</param>
        public SyncMetadataResponse(StatusEnum? status = default, int? tablesUpdated = default, int? columnsUpdated = default, int? tablesFailed = default, int? columnsFailed = default, string message = default)
        {
            this.Status = status;
            this.TablesUpdated = tablesUpdated;
            this.ColumnsUpdated = columnsUpdated;
            this.TablesFailed = tablesFailed;
            this.ColumnsFailed = columnsFailed;
            this.Message = message;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Number of tables with metadata updates.
        /// </summary>
        /// <value>Number of tables with metadata updates.</value>
        [DataMember(Name = "tables_updated", EmitDefaultValue = true)]
        public int? TablesUpdated { get; set; }

        /// <summary>
        /// Number of columns with metadata updates.
        /// </summary>
        /// <value>Number of columns with metadata updates.</value>
        [DataMember(Name = "columns_updated", EmitDefaultValue = true)]
        public int? ColumnsUpdated { get; set; }

        /// <summary>
        /// Number of tables that failed to sync (for PARTIAL_SUCCESS).
        /// </summary>
        /// <value>Number of tables that failed to sync (for PARTIAL_SUCCESS).</value>
        [DataMember(Name = "tables_failed", EmitDefaultValue = true)]
        public int? TablesFailed { get; set; }

        /// <summary>
        /// Number of columns that failed to sync (for PARTIAL_SUCCESS).
        /// </summary>
        /// <value>Number of columns that failed to sync (for PARTIAL_SUCCESS).</value>
        [DataMember(Name = "columns_failed", EmitDefaultValue = true)]
        public int? ColumnsFailed { get; set; }

        /// <summary>
        /// Message describing the result.
        /// </summary>
        /// <value>Message describing the result.</value>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SyncMetadataResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TablesUpdated: ").Append(TablesUpdated).Append("\n");
            sb.Append("  ColumnsUpdated: ").Append(ColumnsUpdated).Append("\n");
            sb.Append("  TablesFailed: ").Append(TablesFailed).Append("\n");
            sb.Append("  ColumnsFailed: ").Append(ColumnsFailed).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
