/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// Credential ThoughtSpot uses to reach an Org&#39;s repository.
    /// </summary>
    [DataContract(Name = "VersionControlCredentialInput")]
    public partial class VersionControlCredentialInput : IValidatableObject
    {
        /// <summary>
        /// How the credential is held.
        /// </summary>
        /// <value>How the credential is held.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum ACCESSTOKEN for value: ACCESS_TOKEN
            /// </summary>
            [EnumMember(Value = "ACCESS_TOKEN")]
            ACCESSTOKEN = 1
        }


        /// <summary>
        /// How the credential is held.
        /// </summary>
        /// <value>How the credential is held.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionControlCredentialInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VersionControlCredentialInput()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionControlCredentialInput" /> class.
        /// </summary>
        /// <param name="type">How the credential is held. (required).</param>
        /// <param name="username">Username presented with the token over HTTPS, for example svc-version-control..</param>
        /// <param name="accessToken">Access token granting repository contents read and write, and metadata read. Add the provider&#39;s repository-rules read permission for rule-aware validation. Required when type is ACCESS_TOKEN..</param>
        public VersionControlCredentialInput(TypeEnum type = default, string username = default, string accessToken = default)
        {
            this.Type = type;
            this.Username = username;
            this.AccessToken = accessToken;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Username presented with the token over HTTPS, for example svc-version-control.
        /// </summary>
        /// <value>Username presented with the token over HTTPS, for example svc-version-control.</value>
        [DataMember(Name = "username", EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Access token granting repository contents read and write, and metadata read. Add the provider&#39;s repository-rules read permission for rule-aware validation. Required when type is ACCESS_TOKEN.
        /// </summary>
        /// <value>Access token granting repository contents read and write, and metadata read. Add the provider&#39;s repository-rules read permission for rule-aware validation. Required when type is ACCESS_TOKEN.</value>
        [DataMember(Name = "access_token", EmitDefaultValue = true)]
        public string AccessToken { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VersionControlCredentialInput {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
