/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.RestApi.Sdk.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.RestApi.Sdk.Client.OpenAPIDateConverter;

namespace ThoughtSpot.RestApi.Sdk.Model
{
    /// <summary>
    /// WebhookDeleteResponse
    /// </summary>
    [DataContract(Name = "WebhookDeleteResponse")]
    public partial class WebhookDeleteResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookDeleteResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebhookDeleteResponse()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookDeleteResponse" /> class.
        /// </summary>
        /// <param name="deletedCount">Number of webhooks successfully deleted. (required).</param>
        /// <param name="failedCount">Number of webhooks that failed to delete. (required).</param>
        /// <param name="deletedWebhooks">List of successfully deleted webhooks. (required).</param>
        /// <param name="failedWebhooks">List of webhooks that failed to delete with error details. (required).</param>
        public WebhookDeleteResponse(int deletedCount = default, int failedCount = default, List<WebhookResponse> deletedWebhooks = default, List<WebhookDeleteFailure> failedWebhooks = default)
        {
            this.DeletedCount = deletedCount;
            this.FailedCount = failedCount;
            // to ensure "deletedWebhooks" is required (not null)
            if (deletedWebhooks == null)
            {
                throw new ArgumentNullException("deletedWebhooks is a required property for WebhookDeleteResponse and cannot be null");
            }
            this.DeletedWebhooks = deletedWebhooks;
            // to ensure "failedWebhooks" is required (not null)
            if (failedWebhooks == null)
            {
                throw new ArgumentNullException("failedWebhooks is a required property for WebhookDeleteResponse and cannot be null");
            }
            this.FailedWebhooks = failedWebhooks;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Number of webhooks successfully deleted.
        /// </summary>
        /// <value>Number of webhooks successfully deleted.</value>
        [DataMember(Name = "deleted_count", IsRequired = true, EmitDefaultValue = true)]
        public int DeletedCount { get; set; }

        /// <summary>
        /// Number of webhooks that failed to delete.
        /// </summary>
        /// <value>Number of webhooks that failed to delete.</value>
        [DataMember(Name = "failed_count", IsRequired = true, EmitDefaultValue = true)]
        public int FailedCount { get; set; }

        /// <summary>
        /// List of successfully deleted webhooks.
        /// </summary>
        /// <value>List of successfully deleted webhooks.</value>
        [DataMember(Name = "deleted_webhooks", IsRequired = true, EmitDefaultValue = true)]
        public List<WebhookResponse> DeletedWebhooks { get; set; }

        /// <summary>
        /// List of webhooks that failed to delete with error details.
        /// </summary>
        /// <value>List of webhooks that failed to delete with error details.</value>
        [DataMember(Name = "failed_webhooks", IsRequired = true, EmitDefaultValue = true)]
        public List<WebhookDeleteFailure> FailedWebhooks { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookDeleteResponse {\n");
            sb.Append("  DeletedCount: ").Append(DeletedCount).Append("\n");
            sb.Append("  FailedCount: ").Append(FailedCount).Append("\n");
            sb.Append("  DeletedWebhooks: ").Append(DeletedWebhooks).Append("\n");
            sb.Append("  FailedWebhooks: ").Append(FailedWebhooks).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
