/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.Client.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.Client.Client.OpenAPIDateConverter;

namespace ThoughtSpot.Client.Model
{
    /// <summary>
    /// Cluster-level non-embed access configuration.
    /// </summary>
    [DataContract(Name = "ClusterNonEmbedAccess")]
    public partial class ClusterNonEmbedAccess : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClusterNonEmbedAccess" /> class.
        /// </summary>
        /// <param name="blockFullAppAccess">Block full application access for non-embedded usage..</param>
        /// <param name="groupsWithAccess">Groups that have non-embed full app access. Only applicable when orgs feature is disabled. Use org_preferences when org feature is enabled..</param>
        public ClusterNonEmbedAccess(bool? blockFullAppAccess = default(bool?), List<GroupInfo> groupsWithAccess = default(List<GroupInfo>))
        {
            this.BlockFullAppAccess = blockFullAppAccess;
            this.GroupsWithAccess = groupsWithAccess;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Block full application access for non-embedded usage.
        /// </summary>
        /// <value>Block full application access for non-embedded usage.</value>
        [DataMember(Name = "block_full_app_access", EmitDefaultValue = true)]
        public bool? BlockFullAppAccess { get; set; }

        /// <summary>
        /// Groups that have non-embed full app access. Only applicable when orgs feature is disabled. Use org_preferences when org feature is enabled.
        /// </summary>
        /// <value>Groups that have non-embed full app access. Only applicable when orgs feature is disabled. Use org_preferences when org feature is enabled.</value>
        [DataMember(Name = "groups_with_access", EmitDefaultValue = true)]
        public List<GroupInfo> GroupsWithAccess { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClusterNonEmbedAccess {\n");
            sb.Append("  BlockFullAppAccess: ").Append(BlockFullAppAccess).Append("\n");
            sb.Append("  GroupsWithAccess: ").Append(GroupsWithAccess).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
