/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.Client.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.Client.Client.OpenAPIDateConverter;

namespace ThoughtSpot.Client.Model
{
    /// <summary>
    /// DataSource
    /// </summary>
    [DataContract(Name = "DataSource")]
    public partial class DataSource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataSource" /> class.
        /// </summary>
        /// <param name="confidence">Confidence score for the data source suggestion..</param>
        /// <param name="details">details.</param>
        /// <param name="reasoning">LLM reasoning for the data source..</param>
        public DataSource(float? confidence = default(float?), EntityHeader details = default(EntityHeader), string reasoning = default(string))
        {
            this.Confidence = confidence;
            this.Details = details;
            this.Reasoning = reasoning;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Confidence score for the data source suggestion.
        /// </summary>
        /// <value>Confidence score for the data source suggestion.</value>
        [DataMember(Name = "confidence", EmitDefaultValue = true)]
        public float? Confidence { get; set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [DataMember(Name = "details", EmitDefaultValue = false)]
        public EntityHeader Details { get; set; }

        /// <summary>
        /// LLM reasoning for the data source.
        /// </summary>
        /// <value>LLM reasoning for the data source.</value>
        [DataMember(Name = "reasoning", EmitDefaultValue = true)]
        public string Reasoning { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataSource {\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Reasoning: ").Append(Reasoning).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
