/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.Client.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.Client.Client.OpenAPIDateConverter;

namespace ThoughtSpot.Client.Model
{
    /// <summary>
    /// FavoriteMetadataItem
    /// </summary>
    [DataContract(Name = "FavoriteMetadataItem")]
    public partial class FavoriteMetadataItem : IValidatableObject
    {
        /// <summary>
        ///   Type of metadata object.     Required if the name of the object is set as the identifier. This attribute is optional when the object GUID is specified as the identifier.
        /// </summary>
        /// <value>  Type of metadata object.     Required if the name of the object is set as the identifier. This attribute is optional when the object GUID is specified as the identifier.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum LIVEBOARD for value: LIVEBOARD
            /// </summary>
            [EnumMember(Value = "LIVEBOARD")]
            LIVEBOARD = 1,

            /// <summary>
            /// Enum ANSWER for value: ANSWER
            /// </summary>
            [EnumMember(Value = "ANSWER")]
            ANSWER = 2,

            /// <summary>
            /// Enum LOGICALTABLE for value: LOGICAL_TABLE
            /// </summary>
            [EnumMember(Value = "LOGICAL_TABLE")]
            LOGICALTABLE = 3,

            /// <summary>
            /// Enum LOGICALCOLUMN for value: LOGICAL_COLUMN
            /// </summary>
            [EnumMember(Value = "LOGICAL_COLUMN")]
            LOGICALCOLUMN = 4,

            /// <summary>
            /// Enum CONNECTION for value: CONNECTION
            /// </summary>
            [EnumMember(Value = "CONNECTION")]
            CONNECTION = 5,

            /// <summary>
            /// Enum TAG for value: TAG
            /// </summary>
            [EnumMember(Value = "TAG")]
            TAG = 6,

            /// <summary>
            /// Enum USER for value: USER
            /// </summary>
            [EnumMember(Value = "USER")]
            USER = 7,

            /// <summary>
            /// Enum USERGROUP for value: USER_GROUP
            /// </summary>
            [EnumMember(Value = "USER_GROUP")]
            USERGROUP = 8,

            /// <summary>
            /// Enum LOGICALRELATIONSHIP for value: LOGICAL_RELATIONSHIP
            /// </summary>
            [EnumMember(Value = "LOGICAL_RELATIONSHIP")]
            LOGICALRELATIONSHIP = 9
        }


        /// <summary>
        ///   Type of metadata object.     Required if the name of the object is set as the identifier. This attribute is optional when the object GUID is specified as the identifier.
        /// </summary>
        /// <value>  Type of metadata object.     Required if the name of the object is set as the identifier. This attribute is optional when the object GUID is specified as the identifier.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FavoriteMetadataItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FavoriteMetadataItem()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FavoriteMetadataItem" /> class.
        /// </summary>
        /// <param name="id">Unique ID of the metadata object. (required).</param>
        /// <param name="name">name of the metadata object. (required).</param>
        /// <param name="type">  Type of metadata object.     Required if the name of the object is set as the identifier. This attribute is optional when the object GUID is specified as the identifier. (required).</param>
        public FavoriteMetadataItem(string id = default(string), string name = default(string), TypeEnum type = default(TypeEnum))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for FavoriteMetadataItem and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for FavoriteMetadataItem and cannot be null");
            }
            this.Name = name;
            this.Type = type;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Unique ID of the metadata object.
        /// </summary>
        /// <value>Unique ID of the metadata object.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// name of the metadata object.
        /// </summary>
        /// <value>name of the metadata object.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FavoriteMetadataItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
