/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.Client.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.Client.Client.OpenAPIDateConverter;

namespace ThoughtSpot.Client.Model
{
    /// <summary>
    /// SendAgentMessageResponse
    /// </summary>
    [DataContract(Name = "SendAgentMessageResponse")]
    public partial class SendAgentMessageResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendAgentMessageResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendAgentMessageResponse()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendAgentMessageResponse" /> class.
        /// </summary>
        /// <param name="success">Indicates whether the agent response was received and processed successfully. (required).</param>
        /// <param name="message">Optional message providing additional context about the operation outcome..</param>
        public SendAgentMessageResponse(bool success = default(bool), string message = default(string))
        {
            this.Success = success;
            this.Message = message;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Indicates whether the agent response was received and processed successfully.
        /// </summary>
        /// <value>Indicates whether the agent response was received and processed successfully.</value>
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Optional message providing additional context about the operation outcome.
        /// </summary>
        /// <value>Optional message providing additional context about the operation outcome.</value>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendAgentMessageResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
