/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ThoughtSpot.Client.Client.FileParameter;
using OpenAPIDateConverter = ThoughtSpot.Client.Client.OpenAPIDateConverter;

namespace ThoughtSpot.Client.Model
{
    /// <summary>
    /// SyncMetadataRequest
    /// </summary>
    [DataContract(Name = "SyncMetadataRequest")]
    public partial class SyncMetadataRequest : IValidatableObject
    {
        /// <summary>
        /// Defines SyncAttributes
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SyncAttributesEnum
        {
            /// <summary>
            /// Enum DESCRIPTION for value: DESCRIPTION
            /// </summary>
            [EnumMember(Value = "DESCRIPTION")]
            DESCRIPTION = 1
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SyncMetadataRequest" /> class.
        /// </summary>
        /// <param name="tables">Array of tables to sync. Each element can be: - String: Table identifier (GUID or name) to sync   all columns for that table. - Object: {tableId: [columnIds]} to sync specific   columns. If not provided, syncs all tables in the connection..</param>
        /// <param name="syncAttributes">List of sync_attributes to sync from CDW. The default value is DESCRIPTION..</param>
        public SyncMetadataRequest(Object tables = default(Object), List<SyncAttributesEnum> syncAttributes = default(List<SyncAttributesEnum>))
        {
            this.Tables = tables;
            this.SyncAttributes = syncAttributes;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Array of tables to sync. Each element can be: - String: Table identifier (GUID or name) to sync   all columns for that table. - Object: {tableId: [columnIds]} to sync specific   columns. If not provided, syncs all tables in the connection.
        /// </summary>
        /// <value>Array of tables to sync. Each element can be: - String: Table identifier (GUID or name) to sync   all columns for that table. - Object: {tableId: [columnIds]} to sync specific   columns. If not provided, syncs all tables in the connection.</value>
        [DataMember(Name = "tables", EmitDefaultValue = false)]
        public Object Tables { get; set; }

        /// <summary>
        /// List of sync_attributes to sync from CDW. The default value is DESCRIPTION.
        /// </summary>
        /// <value>List of sync_attributes to sync from CDW. The default value is DESCRIPTION.</value>
        [DataMember(Name = "sync_attributes", EmitDefaultValue = false)]
        public List<SyncMetadataRequest.SyncAttributesEnum> SyncAttributes { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SyncMetadataRequest {\n");
            sb.Append("  Tables: ").Append(Tables).Append("\n");
            sb.Append("  SyncAttributes: ").Append(SyncAttributes).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
