# -*- coding: utf-8 -*-

"""
thoughtspotpublicrestapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortOrder1Enum(object):

    """Implementation of the 'SortOrder1' enum.

    Order in which sortBy should be applied. Valid values

    Attributes:
        DEFAULT: TODO: type description here.
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    DEFAULT = 'DEFAULT'

    ASC = 'ASC'

    DESC = 'DESC'
