/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActionDetailsInputCreate } from '../models/ActionDetailsInputCreate';
import { AssociateMetadataInputCreate } from '../models/AssociateMetadataInputCreate';
import { DefaultActionConfigInputCreate } from '../models/DefaultActionConfigInputCreate';
import { HttpFile } from '../http/http';

export class CreateCustomActionRequest {
    /**
    * Name of the custom action. The custom action name must be unique.
    */
    'name': string;
    'action_details': ActionDetailsInputCreate;
    /**
    * Metadata objects to which the custom action needs to be associated.
    */
    'associate_metadata'?: Array<AssociateMetadataInputCreate>;
    'default_action_config'?: DefaultActionConfigInputCreate;
    /**
    * Unique ID or name of the groups that can view and access the custom action.
    */
    'group_identifiers'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "action_details",
            "baseName": "action_details",
            "type": "ActionDetailsInputCreate",
            "format": ""
        },
        {
            "name": "associate_metadata",
            "baseName": "associate_metadata",
            "type": "Array<AssociateMetadataInputCreate>",
            "format": ""
        },
        {
            "name": "default_action_config",
            "baseName": "default_action_config",
            "type": "DefaultActionConfigInputCreate",
            "format": ""
        },
        {
            "name": "group_identifiers",
            "baseName": "group_identifiers",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCustomActionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

