/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ThoughtSpot.Client.Model;
using ThoughtSpot.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ThoughtSpot.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateObjIdInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateObjIdInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateObjIdInput
        //private UpdateObjIdInput instance;

        public UpdateObjIdInputTests()
        {
            // TODO uncomment below to create an instance of UpdateObjIdInput
            //instance = new UpdateObjIdInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateObjIdInput
        /// </summary>
        [Fact]
        public void UpdateObjIdInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateObjIdInput
            //Assert.IsType<UpdateObjIdInput>(instance);
        }

        /// <summary>
        /// Test the property 'MetadataIdentifier'
        /// </summary>
        [Fact]
        public void MetadataIdentifierTest()
        {
            // TODO unit test for the property 'MetadataIdentifier'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'CurrentObjId'
        /// </summary>
        [Fact]
        public void CurrentObjIdTest()
        {
            // TODO unit test for the property 'CurrentObjId'
        }

        /// <summary>
        /// Test the property 'NewObjId'
        /// </summary>
        [Fact]
        public void NewObjIdTest()
        {
            // TODO unit test for the property 'NewObjId'
        }
    }
}
