/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ThoughtSpot.Client.Client;
using ThoughtSpot.Client.Api;
// uncomment below to import models
//using ThoughtSpot.Client.Model;

namespace ThoughtSpot.Client.Test.Api
{
    /// <summary>
    ///  Class for testing CustomActionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CustomActionApiTests : IDisposable
    {
        private CustomActionApi instance;

        public CustomActionApiTests()
        {
            instance = new CustomActionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomActionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CustomActionApi
            //Assert.IsType<CustomActionApi>(instance);
        }

        /// <summary>
        /// Test CreateCustomAction
        /// </summary>
        [Fact]
        public void CreateCustomActionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCustomActionRequest createCustomActionRequest = null;
            //var response = instance.CreateCustomAction(createCustomActionRequest);
            //Assert.IsType<ResponseCustomAction>(response);
        }

        /// <summary>
        /// Test DeleteCustomAction
        /// </summary>
        [Fact]
        public void DeleteCustomActionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customActionIdentifier = null;
            //instance.DeleteCustomAction(customActionIdentifier);
        }

        /// <summary>
        /// Test SearchCustomActions
        /// </summary>
        [Fact]
        public void SearchCustomActionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchCustomActionsRequest searchCustomActionsRequest = null;
            //var response = instance.SearchCustomActions(searchCustomActionsRequest);
            //Assert.IsType<List<ResponseCustomAction>>(response);
        }

        /// <summary>
        /// Test UpdateCustomAction
        /// </summary>
        [Fact]
        public void UpdateCustomActionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customActionIdentifier = null;
            //UpdateCustomActionRequest updateCustomActionRequest = null;
            //instance.UpdateCustomAction(customActionIdentifier, updateCustomActionRequest);
        }
    }
}
