/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ThoughtSpot.Client.Client;
using ThoughtSpot.Client.Api;
// uncomment below to import models
//using ThoughtSpot.Client.Model;

namespace ThoughtSpot.Client.Test.Api
{
    /// <summary>
    ///  Class for testing StyleCustomizationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StyleCustomizationApiTests : IDisposable
    {
        private StyleCustomizationApi instance;

        public StyleCustomizationApiTests()
        {
            instance = new StyleCustomizationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StyleCustomizationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StyleCustomizationApi
            //Assert.IsType<StyleCustomizationApi>(instance);
        }

        /// <summary>
        /// Test DeleteStyleFonts
        /// </summary>
        [Fact]
        public void DeleteStyleFontsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeleteStyleFontsRequest deleteStyleFontsRequest = null;
            //var response = instance.DeleteStyleFonts(deleteStyleFontsRequest);
            //Assert.IsType<StyleFontDeleteData>(response);
        }

        /// <summary>
        /// Test ExportStyleLogos
        /// </summary>
        [Fact]
        public void ExportStyleLogosTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ExportStyleLogosRequest exportStyleLogosRequest = null;
            //var response = instance.ExportStyleLogos(exportStyleLogosRequest);
            //Assert.IsType<FileParameter>(response);
        }

        /// <summary>
        /// Test SearchStyleCustomizations
        /// </summary>
        [Fact]
        public void SearchStyleCustomizationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchStyleCustomizationsRequest searchStyleCustomizationsRequest = null;
            //var response = instance.SearchStyleCustomizations(searchStyleCustomizationsRequest);
            //Assert.IsType<List<StylePreference>>(response);
        }

        /// <summary>
        /// Test SearchStyleFonts
        /// </summary>
        [Fact]
        public void SearchStyleFontsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SearchStyleFontsRequest searchStyleFontsRequest = null;
            //var response = instance.SearchStyleFonts(searchStyleFontsRequest);
            //Assert.IsType<List<StyleFontRecord>>(response);
        }

        /// <summary>
        /// Test UpdateStyleCustomization
        /// </summary>
        [Fact]
        public void UpdateStyleCustomizationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string scope = null;
            //string? operation = null;
            //StyleResetOptionsInput? resetOptions = null;
            //NavigationPanelInput? navigationPanel = null;
            //StyleColorPaletteInput? chartColorPalette = null;
            //string? embeddedFooterText = null;
            //VisualizationFontsInput? visualizationFonts = null;
            //FileParameter? defaultLogo = null;
            //FileParameter? wideLogo = null;
            //instance.UpdateStyleCustomization(scope, operation, resetOptions, navigationPanel, chartColorPalette, embeddedFooterText, visualizationFonts, defaultLogo, wideLogo);
        }

        /// <summary>
        /// Test UpdateStyleFont
        /// </summary>
        [Fact]
        public void UpdateStyleFontTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fontIdentifier = null;
            //UpdateStyleFontRequest updateStyleFontRequest = null;
            //instance.UpdateStyleFont(fontIdentifier, updateStyleFontRequest);
        }

        /// <summary>
        /// Test UploadStyleFont
        /// </summary>
        [Fact]
        public void UploadStyleFontTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //FileParameter fileContent = null;
            //string? scope = null;
            //string? weight = null;
            //string? style = null;
            //string? color = null;
            //var response = instance.UploadStyleFont(name, fileContent, scope, weight, style, color);
            //Assert.IsType<StyleFontUploadData>(response);
        }
    }
}
