/**
 * RESTAPI SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TspublicRestV2OrgUpdateRequest {
  /** Name of the organization. */
  name?: string;
  /** The ID of the organization. */
  id?: string;
  /** Description text for the organization. */
  description?: string;
}

export const tspublicRestV2OrgUpdateRequestSchema: Schema<TspublicRestV2OrgUpdateRequest> = object(
  {
    name: ['name', optional(string())],
    id: ['id', optional(string())],
    description: ['description', optional(string())],
  }
);
