/**
 * RESTAPI SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  SearchPermissionOnObjectsIncludeDependentEnum,
  searchPermissionOnObjectsIncludeDependentEnumSchema,
} from './searchPermissionOnObjectsIncludeDependentEnum';
import {
  TsObjectSearchInput,
  tsObjectSearchInputSchema,
} from './tsObjectSearchInput';
import {
  UserNameAndIDInput,
  userNameAndIDInputSchema,
} from './userNameAndIDInput';

export interface TspublicRestV2SecurityPermissionTsobjectSearchRequest {
  /** A JSON Array of GUIDs and type of metadata object. */
  tsObject: TsObjectSearchInput[];
  /** A JSON array of principal names or GUIDs. When both are given then id is considered. */
  principal?: UserNameAndIDInput[];
  /** When this field is set to true, the API response includes the permission details for the dependent objects */
  includeDependent?: SearchPermissionOnObjectsIncludeDependentEnum;
}

export const tspublicRestV2SecurityPermissionTsobjectSearchRequestSchema: Schema<TspublicRestV2SecurityPermissionTsobjectSearchRequest> = object(
  {
    tsObject: ['tsObject', array(lazy(() => tsObjectSearchInputSchema))],
    principal: [
      'principal',
      optional(array(lazy(() => userNameAndIDInputSchema))),
    ],
    includeDependent: [
      'includeDependent',
      optional(searchPermissionOnObjectsIncludeDependentEnumSchema),
    ],
  }
);
