/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Font assignment for a single advanced chart visualization area.
*/
export class AdvancedChartFontAssignmentInput {
    /**
    * Advanced chart visualization area to assign the font to.    Version: 26.7.0.cl or later 
    */
    'visualization_area': AdvancedChartFontAssignmentInputVisualizationAreaEnum;
    /**
    * UUID or name of the font to assign to this area.    Version: 26.7.0.cl or later 
    */
    'font_identifier': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "visualization_area",
            "baseName": "visualization_area",
            "type": "AdvancedChartFontAssignmentInputVisualizationAreaEnum",
            "format": ""
        },
        {
            "name": "font_identifier",
            "baseName": "font_identifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AdvancedChartFontAssignmentInput.attributeTypeMap;
    }

    public constructor() {
    }
}


export type AdvancedChartFontAssignmentInputVisualizationAreaEnum = "ADVANCED_CHART_LABELS" ;

