/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Event specification for channel history search.
*/
export class ChannelHistoryEventInput {
    /**
    * Type of the event.
    */
    'type': ChannelHistoryEventInputTypeEnum;
    /**
    * Unique ID or name of the event.
    */
    'identifier'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ChannelHistoryEventInputTypeEnum",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelHistoryEventInput.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ChannelHistoryEventInputTypeEnum = "LIVEBOARD_SCHEDULE" ;

