/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Font assignment for a single chart visualization area.
*/
export class ChartFontAssignmentInput {
    /**
    * Chart visualization area to assign the font to.
    */
    'visualization_area': ChartFontAssignmentInputVisualizationAreaEnum;
    /**
    * UUID or name of the font to assign to this area.
    */
    'font_identifier': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "visualization_area",
            "baseName": "visualization_area",
            "type": "ChartFontAssignmentInputVisualizationAreaEnum",
            "format": ""
        },
        {
            "name": "font_identifier",
            "baseName": "font_identifier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChartFontAssignmentInput.attributeTypeMap;
    }

    public constructor() {
    }
}

    export type ChartFontAssignmentInputVisualizationAreaEnum = "CHART_X_AXIS_LABELS" | "CHART_X_AXIS_TITLE" | "CHART_Y_AXIS_LABELS" | "CHART_Y_AXIS_TITLE" | "CHART_TOOLTIP" | "CHART_SCATTER_DATA_LABELS" | "CHART_DONUT_DATA_LABELS" | "CHART_LINE_DATA_LABELS" | "CHART_COLUMN_DATA_LABELS" | "CHART_BAR_DATA_LABELS" | "CHART_AREA_DATA_LABELS" ;

