/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DeployRevisionRequest {
    /**
    * Revision to deploy, for example a Git commit SHA. Omit this to resolve and pin the head of your Org\'s configured branch. Either way the revision must be reachable from that branch.
    */
    'target_revision'?: string;
    /**
    * What to compare the revision against. DELTA compares it with the revision this Org last received, which is what makes the Org converge on the branch. FULL ignores the deploy marker, treats every object at the revision as a change, and observes no removals.
    */
    'deploy_type'?: DeployRevisionRequestDeployTypeEnum;
    /**
    * How far the run goes and how it settles per-object failures.
    */
    'deploy_policy'?: DeployRevisionRequestDeployPolicyEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "target_revision",
            "baseName": "target_revision",
            "type": "string",
            "format": ""
        },
        {
            "name": "deploy_type",
            "baseName": "deploy_type",
            "type": "DeployRevisionRequestDeployTypeEnum",
            "format": ""
        },
        {
            "name": "deploy_policy",
            "baseName": "deploy_policy",
            "type": "DeployRevisionRequestDeployPolicyEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeployRevisionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

    export type DeployRevisionRequestDeployTypeEnum = "DELTA" | "FULL" ;
    export type DeployRevisionRequestDeployPolicyEnum = "ALL_OR_NONE" | "PARTIAL" | "VALIDATE_ONLY" ;

