/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EventChannelConfig {
    /**
    * Type of event for which communication channels are configured
    */
    'event_type': EventChannelConfigEventTypeEnum;
    /**
    * Communication channels enabled for this event type. Empty array indicates no channels are enabled.
    */
    'channels': Array<EventChannelConfigChannelsEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "event_type",
            "baseName": "event_type",
            "type": "EventChannelConfigEventTypeEnum",
            "format": ""
        },
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<EventChannelConfigChannelsEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventChannelConfig.attributeTypeMap;
    }

    public constructor() {
    }
}


export type EventChannelConfigEventTypeEnum = "LIVEBOARD_SCHEDULE" ;
export type EventChannelConfigChannelsEnum = "EMAIL" | "WEBHOOK" ;

