/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* One per-item import failure surfaced by importMemory. `line_number` is the best-effort line number in the uploaded YAML; `field_name` is a dotted path within the item (e.g. `content.rule_definition`) for inline highlighting; absent when the failure is item-level rather than field-level.
*/
export class ImportFailure {
    /**
    * Best-effort line number of the offending item in the uploaded YAML. May be null when the line cannot be determined.
    */
    'line_number'?: number | null;
    /**
    * Machine-readable category for the failure (e.g. `VALIDATION`, `ACCESS_DENIED`, `CHAR_LIMIT`).
    */
    'reason'?: ImportFailureReasonEnum | null;
    /**
    * Dotted path to the offending field within the item (e.g. `content.rule_definition`) for inline highlighting. Absent when the failure is item-level rather than field-level.
    */
    'field_name'?: string | null;
    /**
    * Human-readable description of the failure.
    */
    'message'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "line_number",
            "baseName": "line_number",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "ImportFailureReasonEnum",
            "format": ""
        },
        {
            "name": "field_name",
            "baseName": "field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImportFailure.attributeTypeMap;
    }

    public constructor() {
    }
}

    export type ImportFailureReasonEnum = "UNKNOWN_FAILURE_REASON" | "VALIDATION" | "UNRESOLVED_SOURCE" | "ACCESS_DENIED" | "CHAR_LIMIT" | "SCHEMA" ;

