/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ImportMemoryRequest {
    /**
    * The full serialized memory payload to import (currently YAML) — typically a previous `exportMemory` response\'s `content`, edited locally and re-submitted.
    */
    'content': string;
    /**
    * Required. When `true`, validate the payload and return preview counts and row failures without writing anything. Pass `false` to apply the atomic replacement. The caller must choose explicitly so a real import is never triggered by omission.
    */
    'dry_run': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "dry_run",
            "baseName": "dry_run",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImportMemoryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

