/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PrincipalsInput } from '../models/PrincipalsInput';
import { HttpFile } from '../http/http';

export class ManageObjectPrivilegeRequest {
    /**
    * Operation to perform to manage object privileges. Available operations are: `ADD`, `REMOVE`.
    */
    'operation': ManageObjectPrivilegeRequestOperationEnum;
    /**
    * Type of metadata objects on which you want to perform the operation. For now only LOGICAL_TABLE is supported. It may be extended to other metadata types in the future.
    */
    'metadata_type': ManageObjectPrivilegeRequestMetadataTypeEnum;
    /**
    * List of object privilege types on which you want to perform the operation.
    */
    'object_privilege_types': Array<ManageObjectPrivilegeRequestObjectPrivilegeTypesEnum>;
    /**
    * List of metadata identifiers (GUID or name) on which you want to perform the operation.
    */
    'metadata_identifiers': Array<string>;
    /**
    * User or group objects (GUID or name) to which you want to apply the given operation and given object privileges.
    */
    'principals': Array<PrincipalsInput>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "operation",
            "baseName": "operation",
            "type": "ManageObjectPrivilegeRequestOperationEnum",
            "format": ""
        },
        {
            "name": "metadata_type",
            "baseName": "metadata_type",
            "type": "ManageObjectPrivilegeRequestMetadataTypeEnum",
            "format": ""
        },
        {
            "name": "object_privilege_types",
            "baseName": "object_privilege_types",
            "type": "Array<ManageObjectPrivilegeRequestObjectPrivilegeTypesEnum>",
            "format": ""
        },
        {
            "name": "metadata_identifiers",
            "baseName": "metadata_identifiers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "principals",
            "baseName": "principals",
            "type": "Array<PrincipalsInput>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ManageObjectPrivilegeRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ManageObjectPrivilegeRequestOperationEnum = "ADD" | "REMOVE" ;
export type ManageObjectPrivilegeRequestMetadataTypeEnum = "LOGICAL_TABLE" ;
export type ManageObjectPrivilegeRequestObjectPrivilegeTypesEnum = "SPOTTER_COACHING_PRIVILEGE" ;

