/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VariableDetailInput } from '../models/VariableDetailInput';
import { HttpFile } from '../http/http';

export class SearchVariablesRequest {
    /**
    * Variable details
    */
    'variable_details'?: Array<VariableDetailInput>;
    /**
    * The starting record number from where the records should be included
    */
    'record_offset'?: number;
    /**
    * The number of records that should be included
    */
    'record_size'?: number;
    /**
    * Format in which we want the output
    */
    'output_format'?: SearchVariablesRequestOutputFormatEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "variable_details",
            "baseName": "variable_details",
            "type": "Array<VariableDetailInput>",
            "format": ""
        },
        {
            "name": "record_offset",
            "baseName": "record_offset",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "record_size",
            "baseName": "record_size",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "output_format",
            "baseName": "output_format",
            "type": "SearchVariablesRequestOutputFormatEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchVariablesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SearchVariablesRequestOutputFormatEnum = "METADATA_ONLY" | "METADATA_AND_VALUES" | "EDITABLE_METADATA_AND_VALUES" ;

