/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* App color theme configuration for a specific scope -- the same stored color StyleNavigationPanel expresses, as a brand color plus how it is applied. Returned alongside navigation_panel when the app color theme is enabled on the cluster; omitted otherwise.
*/
export class StyleAppColorTheme {
    /**
    * Brand color as a 6-digit hex string. Null when no brand color is set at this scope.
    */
    'brand_color'?: string | null;
    /**
    * The effective setting: whether the brand color is painted on the top navigation bar literally, instead of the surface shade derived from it. Always the resolved value -- true iff a brand color is set, unless explicitly overridden.
    */
    'apply_as_top_nav_color'?: boolean | null;
    /**
    * True if explicitly set at this scope (either the brand color or the apply_as_top_nav_color choice), overriding any inherited value.
    */
    'is_overridden'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "brand_color",
            "baseName": "brand_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "apply_as_top_nav_color",
            "baseName": "apply_as_top_nav_color",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "is_overridden",
            "baseName": "is_overridden",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StyleAppColorTheme.attributeTypeMap;
    }

    public constructor() {
    }
}
