/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InputVariableValue } from '../models/InputVariableValue';
import { HttpFile } from '../http/http';

/**
* Input for variable value update
*/
export class VariableValueInput {
    /**
    * ID or Name of the variable
    */
    'variable_identifier': string;
    /**
    * Values of the variable
    */
    'variable_values': Array<InputVariableValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "variable_identifier",
            "baseName": "variable_identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "variable_values",
            "baseName": "variable_values",
            "type": "Array<InputVariableValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VariableValueInput.attributeTypeMap;
    }

    public constructor() {
    }
}

