/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* How a promotion is applied.
*/
export class VersionControlPromoteStrategyInput {
    /**
    * How the source is applied to the target branch.
    */
    'type': VersionControlPromoteStrategyInputTypeEnum;
    /**
    * What to do when files conflict.
    */
    'conflict_policy'?: VersionControlPromoteStrategyInputConflictPolicyEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "VersionControlPromoteStrategyInputTypeEnum",
            "format": ""
        },
        {
            "name": "conflict_policy",
            "baseName": "conflict_policy",
            "type": "VersionControlPromoteStrategyInputConflictPolicyEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VersionControlPromoteStrategyInput.attributeTypeMap;
    }

    public constructor() {
    }
}

    export type VersionControlPromoteStrategyInputTypeEnum = "MERGE" | "SQUASH" | "FAST_FORWARD" | "CHERRY_PICK" ;
    export type VersionControlPromoteStrategyInputConflictPolicyEnum = "FAIL_REQUEST" | "USE_SOURCE" | "USE_TARGET" ;

