/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PrincipalsInput } from './principalsInput';

/**
* Details of users or user groups.
*/
export class PermissionInput {
    'principal': PrincipalsInput;
    /**
    * Object share mode.
    */
    'shareMode': PermissionInput.ShareModeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "principal",
            "baseName": "principal",
            "type": "PrincipalsInput"
        },
        {
            "name": "shareMode",
            "baseName": "share_mode",
            "type": "PermissionInput.ShareModeEnum"
        }    ];

    static getAttributeTypeMap() {
        return PermissionInput.attributeTypeMap;
    }
}

export namespace PermissionInput {
    export enum ShareModeEnum {
        ReadOnly = <any> 'READ_ONLY',
        Modify = <any> 'MODIFY',
        NoAccess = <any> 'NO_ACCESS'
    }
}
