/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AnswerContent } from './answerContent';

/**
* Response format associated with the search data API.
*/
export class SearchDataResponse {
    /**
    * Data content of metadata objects.
    */
    'contents': Array<AnswerContent>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contents",
            "baseName": "contents",
            "type": "Array<AnswerContent>"
        }    ];

    static getAttributeTypeMap() {
        return SearchDataResponse.attributeTypeMap;
    }
}

