/**
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateConnectionRequest {
    /**
    * Unique ID or name of the connection.
    */
    'connectionIdentifier': string;
    /**
    * Updated name of the connection.
    */
    'name'?: string;
    /**
    * Updated description of the connection.
    */
    'description'?: string;
    /**
    * Configuration of the data warehouse in JSON.
    */
    'dataWarehouseConfig'?: object;
    /**
    * Indicates whether to validate the connection details.
    */
    'validate'?: boolean | null = true;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connectionIdentifier",
            "baseName": "connection_identifier",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "dataWarehouseConfig",
            "baseName": "data_warehouse_config",
            "type": "object"
        },
        {
            "name": "validate",
            "baseName": "validate",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateConnectionRequest.attributeTypeMap;
    }
}

