/**
 * RESTAPI SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ErrorResponseError } from '../errors/errorResponseError';
import {
  ApiRestV2DependencyRequest,
  apiRestV2DependencyRequestSchema,
} from '../models/apiRestV2DependencyRequest';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class DependencyController extends BaseController {
  /**
   * To create a table in Falcon, use this endpoint.
   *
   * @param body
   * @return Response from the API call
   */
  async getObjectDependency(
    body: ApiRestV2DependencyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('POST', '/api/rest/v2/dependency');
    const mapped = req.prepareArgs({
      body: [body, apiRestV2DependencyRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(500, ErrorResponseError, 'Operation failed or unauthorized request');
    return req.callAsJson(unknown(), requestOptions);
  }
}
