# -*- coding: utf-8 -*-

"""
restapisdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import unittest
from tests.http_response_catcher import HttpResponseCatcher
from restapisdk.configuration import Configuration
from restapisdk.configuration import Environment
from restapisdk.restapisdk_client import RestapisdkClient

class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = RestapisdkClient(config=cls.config)
        cls.auth_managers = cls.client.auth_managers
    @staticmethod
    def create_configuration():
        return Configuration(http_call_back=HttpResponseCatcher())
