/*
 * ThoughtSpot Public REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.thoughtspot.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.thoughtspot.client.model.FilterRules;
import org.thoughtspot.client.model.GroupObject;
import org.thoughtspot.client.model.ParameterValues;
import org.thoughtspot.client.model.TokenAccessScopeObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetCustomAccessTokenRequest
 */
public class GetCustomAccessTokenRequestTest {
    private final GetCustomAccessTokenRequest model = new GetCustomAccessTokenRequest();

    /**
     * Model tests for GetCustomAccessTokenRequest
     */
    @Test
    public void testGetCustomAccessTokenRequest() {
        // TODO: test GetCustomAccessTokenRequest
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'secretKey'
     */
    @Test
    public void secretKeyTest() {
        // TODO: test secretKey
    }

    /**
     * Test the property 'validityTimeInSec'
     */
    @Test
    public void validityTimeInSecTest() {
        // TODO: test validityTimeInSec
    }

    /**
     * Test the property 'orgIdentifier'
     */
    @Test
    public void orgIdentifierTest() {
        // TODO: test orgIdentifier
    }

    /**
     * Test the property 'persistOption'
     */
    @Test
    public void persistOptionTest() {
        // TODO: test persistOption
    }

    /**
     * Test the property 'filterRules'
     */
    @Test
    public void filterRulesTest() {
        // TODO: test filterRules
    }

    /**
     * Test the property 'parameterValues'
     */
    @Test
    public void parameterValuesTest() {
        // TODO: test parameterValues
    }

    /**
     * Test the property 'objects'
     */
    @Test
    public void objectsTest() {
        // TODO: test objects
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'autoCreate'
     */
    @Test
    public void autoCreateTest() {
        // TODO: test autoCreate
    }

}
