# coding: utf-8

"""
    ThoughtSpot Public REST API

    API version: 2.0

    Auto-generated SDK — do not edit this file manually.
    Docs: https://developers.thoughtspot.com/docs/rest-api-sdk
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from thoughtspot_rest_api_sdk.models.response_failed_entities import ResponseFailedEntities
from thoughtspot_rest_api_sdk.models.response_incomplete_entities import ResponseIncompleteEntities
from thoughtspot_rest_api_sdk.models.response_post_upgrade_failed_entities import ResponsePostUpgradeFailedEntities
from thoughtspot_rest_api_sdk.models.response_successful_entities import ResponseSuccessfulEntities
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResponseWorksheetToModelConversion(BaseModel):
    """
    Name of the conversion process, which involves converting worksheets to models.
    """ # noqa: E501
    name: StrictStr
    success_count: StrictInt = Field(description="The number of worksheets successfully converted to models.")
    failure_count: StrictInt = Field(description="The number of worksheets that failed to convert.")
    incomplete_count: StrictInt = Field(description="The number of worksheets that were incomplete during the conversion process.")
    post_upgrade_failed_count: StrictInt = Field(description="The number of worksheets that failed after an upgrade during the conversion process.")
    total_time_in_millis: StrictInt = Field(description="The total time taken to complete the conversion process in milliseconds.")
    successful_entities: ResponseSuccessfulEntities
    failed_entities: ResponseFailedEntities
    incomplete_entities: ResponseIncompleteEntities
    post_upgrade_failed_entities: ResponsePostUpgradeFailedEntities
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "success_count", "failure_count", "incomplete_count", "post_upgrade_failed_count", "total_time_in_millis", "successful_entities", "failed_entities", "incomplete_entities", "post_upgrade_failed_entities"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseWorksheetToModelConversion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of successful_entities
        if self.successful_entities:
            _dict['successful_entities'] = self.successful_entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of failed_entities
        if self.failed_entities:
            _dict['failed_entities'] = self.failed_entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of incomplete_entities
        if self.incomplete_entities:
            _dict['incomplete_entities'] = self.incomplete_entities.to_dict()
        # override the default output from pydantic by calling `to_dict()` of post_upgrade_failed_entities
        if self.post_upgrade_failed_entities:
            _dict['post_upgrade_failed_entities'] = self.post_upgrade_failed_entities.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseWorksheetToModelConversion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "success_count": obj.get("success_count"),
            "failure_count": obj.get("failure_count"),
            "incomplete_count": obj.get("incomplete_count"),
            "post_upgrade_failed_count": obj.get("post_upgrade_failed_count"),
            "total_time_in_millis": obj.get("total_time_in_millis"),
            "successful_entities": ResponseSuccessfulEntities.from_dict(obj["successful_entities"]) if obj.get("successful_entities") is not None else None,
            "failed_entities": ResponseFailedEntities.from_dict(obj["failed_entities"]) if obj.get("failed_entities") is not None else None,
            "incomplete_entities": ResponseIncompleteEntities.from_dict(obj["incomplete_entities"]) if obj.get("incomplete_entities") is not None else None,
            "post_upgrade_failed_entities": ResponsePostUpgradeFailedEntities.from_dict(obj["post_upgrade_failed_entities"]) if obj.get("post_upgrade_failed_entities") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


