# coding: utf-8

"""
    ThoughtSpot Public REST API

    API version: 2.0

    Auto-generated SDK — do not edit this file manually.
    Docs: https://developers.thoughtspot.com/docs/rest-api-sdk
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SchedulesPdfOptionsInput(BaseModel):
    """
    Options for PDF export.
    """ # noqa: E501
    complete_liveboard: Optional[StrictBool] = Field(default=None, description="Indicates whether to include complete Liveboard.")
    include_cover_page: Optional[StrictBool] = Field(default=None, description="Indicates whether to include cover page with the Liveboard title.")
    include_custom_logo: Optional[StrictBool] = Field(default=None, description="Indicates whether to include customized wide logo in the footer if available.")
    include_filter_page: Optional[StrictBool] = Field(default=None, description="Indicates whether to include a page with all applied filters.")
    include_page_number: Optional[StrictBool] = Field(default=None, description="Indicates whether to include page number in the footer of each page")
    page_footer_text: Optional[StrictStr] = Field(default=None, description="Text to include in the footer of each page.")
    page_orientation: Optional[StrictStr] = Field(default=None, description="Page orientation of the PDF.")
    page_size: Optional[StrictStr] = Field(default=None, description="Page size.")
    truncate_table: Optional[StrictBool] = Field(default=None, description="Indicates whether to include only first page of the tables.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["complete_liveboard", "include_cover_page", "include_custom_logo", "include_filter_page", "include_page_number", "page_footer_text", "page_orientation", "page_size", "truncate_table"]

    @field_validator('page_size')
    def page_size_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['A4', 'TAB_BASED']):
            raise ValueError("must be one of enum values ('A4', 'TAB_BASED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchedulesPdfOptionsInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if complete_liveboard (nullable) is None
        # and model_fields_set contains the field
        if self.complete_liveboard is None and "complete_liveboard" in self.model_fields_set:
            _dict['complete_liveboard'] = None

        # set to None if include_cover_page (nullable) is None
        # and model_fields_set contains the field
        if self.include_cover_page is None and "include_cover_page" in self.model_fields_set:
            _dict['include_cover_page'] = None

        # set to None if include_custom_logo (nullable) is None
        # and model_fields_set contains the field
        if self.include_custom_logo is None and "include_custom_logo" in self.model_fields_set:
            _dict['include_custom_logo'] = None

        # set to None if include_filter_page (nullable) is None
        # and model_fields_set contains the field
        if self.include_filter_page is None and "include_filter_page" in self.model_fields_set:
            _dict['include_filter_page'] = None

        # set to None if include_page_number (nullable) is None
        # and model_fields_set contains the field
        if self.include_page_number is None and "include_page_number" in self.model_fields_set:
            _dict['include_page_number'] = None

        # set to None if page_footer_text (nullable) is None
        # and model_fields_set contains the field
        if self.page_footer_text is None and "page_footer_text" in self.model_fields_set:
            _dict['page_footer_text'] = None

        # set to None if page_orientation (nullable) is None
        # and model_fields_set contains the field
        if self.page_orientation is None and "page_orientation" in self.model_fields_set:
            _dict['page_orientation'] = None

        # set to None if page_size (nullable) is None
        # and model_fields_set contains the field
        if self.page_size is None and "page_size" in self.model_fields_set:
            _dict['page_size'] = None

        # set to None if truncate_table (nullable) is None
        # and model_fields_set contains the field
        if self.truncate_table is None and "truncate_table" in self.model_fields_set:
            _dict['truncate_table'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchedulesPdfOptionsInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "complete_liveboard": obj.get("complete_liveboard"),
            "include_cover_page": obj.get("include_cover_page"),
            "include_custom_logo": obj.get("include_custom_logo"),
            "include_filter_page": obj.get("include_filter_page"),
            "include_page_number": obj.get("include_page_number"),
            "page_footer_text": obj.get("page_footer_text"),
            "page_orientation": obj.get("page_orientation"),
            "page_size": obj.get("page_size"),
            "truncate_table": obj.get("truncate_table")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


