# coding: utf-8

"""
    ThoughtSpot Public REST API

    API version: 2.0

    Auto-generated SDK — do not edit this file manually.
    Docs: https://developers.thoughtspot.com/docs/rest-api-sdk
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateRoleRequest(BaseModel):
    """
    UpdateRoleRequest
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the Role.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the Role.")
    privileges: Optional[List[StrictStr]] = Field(default=None, description="Privileges granted to the role. See [Documentation](https://developers.thoughtspot.com/docs/rbac#_role_categories_and_privileges)for supported roles privileges.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "description", "privileges"]

    @field_validator('privileges')
    def privileges_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['USERDATAUPLOADING', 'DATADOWNLOADING', 'DATAMANAGEMENT', 'SHAREWITHALL', 'JOBSCHEDULING', 'A3ANALYSIS', 'BYPASSRLS', 'DISABLE_PINBOARD_CREATION', 'DEVELOPER', 'APPLICATION_ADMINISTRATION', 'USER_ADMINISTRATION', 'GROUP_ADMINISTRATION', 'SYSTEM_INFO_ADMINISTRATION', 'SYNCMANAGEMENT', 'ORG_ADMINISTRATION', 'ROLE_ADMINISTRATION', 'AUTHENTICATION_ADMINISTRATION', 'BILLING_INFO_ADMINISTRATION', 'CONTROL_TRUSTED_AUTH', 'TAGMANAGEMENT', 'LIVEBOARD_VERIFIER', 'CAN_MANAGE_CUSTOM_CALENDAR', 'CAN_CREATE_OR_EDIT_CONNECTIONS', 'CAN_MANAGE_WORKSHEET_VIEWS_TABLES', 'CAN_MANAGE_VERSION_CONTROL', 'THIRDPARTY_ANALYSIS', 'CAN_CREATE_CATALOG', 'CAN_ACCESS_ANALYST_STUDIO', 'CAN_MANAGE_ANALYST_STUDIO', 'CAN_MODIFY_FOLDERS', 'CAN_MANAGE_VARIABLES', 'CAN_VIEW_FOLDERS', 'CAN_MANAGE_AGENTSPOT', 'CAN_ACCESS_AGENTSPOT', 'PREVIEW_DOCUMENT_SEARCH', 'PREVIEW_THOUGHTSPOT_SAGE', 'CAN_MANAGE_WEBHOOKS', 'CAN_DOWNLOAD_VISUALS', 'CAN_DOWNLOAD_DETAILED_DATA', 'CAN_USE_SPOTTER', 'CAN_MANAGE_SPOTTER']):
                raise ValueError("each list item must be one of ('USERDATAUPLOADING', 'DATADOWNLOADING', 'DATAMANAGEMENT', 'SHAREWITHALL', 'JOBSCHEDULING', 'A3ANALYSIS', 'BYPASSRLS', 'DISABLE_PINBOARD_CREATION', 'DEVELOPER', 'APPLICATION_ADMINISTRATION', 'USER_ADMINISTRATION', 'GROUP_ADMINISTRATION', 'SYSTEM_INFO_ADMINISTRATION', 'SYNCMANAGEMENT', 'ORG_ADMINISTRATION', 'ROLE_ADMINISTRATION', 'AUTHENTICATION_ADMINISTRATION', 'BILLING_INFO_ADMINISTRATION', 'CONTROL_TRUSTED_AUTH', 'TAGMANAGEMENT', 'LIVEBOARD_VERIFIER', 'CAN_MANAGE_CUSTOM_CALENDAR', 'CAN_CREATE_OR_EDIT_CONNECTIONS', 'CAN_MANAGE_WORKSHEET_VIEWS_TABLES', 'CAN_MANAGE_VERSION_CONTROL', 'THIRDPARTY_ANALYSIS', 'CAN_CREATE_CATALOG', 'CAN_ACCESS_ANALYST_STUDIO', 'CAN_MANAGE_ANALYST_STUDIO', 'CAN_MODIFY_FOLDERS', 'CAN_MANAGE_VARIABLES', 'CAN_VIEW_FOLDERS', 'CAN_MANAGE_AGENTSPOT', 'CAN_ACCESS_AGENTSPOT', 'PREVIEW_DOCUMENT_SEARCH', 'PREVIEW_THOUGHTSPOT_SAGE', 'CAN_MANAGE_WEBHOOKS', 'CAN_DOWNLOAD_VISUALS', 'CAN_DOWNLOAD_DETAILED_DATA', 'CAN_USE_SPOTTER', 'CAN_MANAGE_SPOTTER')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateRoleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateRoleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "privileges": obj.get("privileges")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


