# coding: utf-8

"""
    ThoughtSpot Public REST API

    API version: 2.0

    Auto-generated SDK — do not edit this file manually.
    Docs: https://developers.thoughtspot.com/docs/rest-api-sdk
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from thoughtspot_rest_api_sdk.models.analyst_source_input import AnalystSourceInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateAnalystRequest(BaseModel):
    """
    UpdateAnalystRequest
    """ # noqa: E501
    name: StrictStr = Field(description="Display name of the analyst.")
    description: StrictStr = Field(description="Description of the analyst. Maximum 200 characters.")
    instructions: Optional[StrictStr] = Field(default=None, description="Natural-language instructions that guide the agent's behavior for this analyst. Omitting this field clears any existing instructions.")
    sources: List[AnalystSourceInput] = Field(description="Data sources the analyst can query. At least one is required, and the caller must have view access to every referenced source. Replaces the existing list in full.")
    mcp_connector_identifiers: Optional[List[StrictStr]] = Field(default=None, description="Identifiers of MCP connectors linked to this analyst. Replaces the existing list in full; omit or pass an empty array to clear.")
    starter_prompts: Optional[List[StrictStr]] = Field(default=None, description="Plain-text starter prompts (max 4, each between 10 and 250 characters; display order follows list position). Replaces the existing list in full; omit or pass an empty array to clear.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "description", "instructions", "sources", "mcp_connector_identifiers", "starter_prompts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAnalystRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item_sources in self.sources:
                if _item_sources:
                    _items.append(_item_sources.to_dict())
            _dict['sources'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAnalystRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "instructions": obj.get("instructions"),
            "sources": [AnalystSourceInput.from_dict(_item) for _item in obj["sources"]] if obj.get("sources") is not None else None,
            "mcp_connector_identifiers": obj.get("mcp_connector_identifiers"),
            "starter_prompts": obj.get("starter_prompts")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


