/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ThoughtSpot.RestApi.Sdk.Model;
using ThoughtSpot.RestApi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ThoughtSpot.RestApi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AgentEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentEvent
        //private AgentEvent instance;

        public AgentEventTests()
        {
            // TODO uncomment below to create an instance of AgentEvent
            //instance = new AgentEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentEvent
        /// </summary>
        [Fact]
        public void AgentEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentEvent
            //Assert.IsType<AgentEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'InvocationId'
        /// </summary>
        [Fact]
        public void InvocationIdTest()
        {
            // TODO unit test for the property 'InvocationId'
        }

        /// <summary>
        /// Test the property 'Partial'
        /// </summary>
        [Fact]
        public void PartialTest()
        {
            // TODO unit test for the property 'Partial'
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
    }
}
