/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ThoughtSpot.RestApi.Sdk.Model;
using ThoughtSpot.RestApi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ThoughtSpot.RestApi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Analyst
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalystTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Analyst
        //private Analyst instance;

        public AnalystTests()
        {
            // TODO uncomment below to create an instance of Analyst
            //instance = new Analyst();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Analyst
        /// </summary>
        [Fact]
        public void AnalystInstanceTest()
        {
            // TODO uncomment below to test "IsType" Analyst
            //Assert.IsType<Analyst>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Fact]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }

        /// <summary>
        /// Test the property 'Sources'
        /// </summary>
        [Fact]
        public void SourcesTest()
        {
            // TODO unit test for the property 'Sources'
        }

        /// <summary>
        /// Test the property 'McpConnectors'
        /// </summary>
        [Fact]
        public void McpConnectorsTest()
        {
            // TODO unit test for the property 'McpConnectors'
        }

        /// <summary>
        /// Test the property 'StarterPrompts'
        /// </summary>
        [Fact]
        public void StarterPromptsTest()
        {
            // TODO unit test for the property 'StarterPrompts'
        }

        /// <summary>
        /// Test the property 'UpdatedTimeInMillis'
        /// </summary>
        [Fact]
        public void UpdatedTimeInMillisTest()
        {
            // TODO unit test for the property 'UpdatedTimeInMillis'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
    }
}
