/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ThoughtSpot.RestApi.Sdk.Model;
using ThoughtSpot.RestApi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ThoughtSpot.RestApi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ImportUserGroupsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImportUserGroupsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImportUserGroupsResponse
        //private ImportUserGroupsResponse instance;

        public ImportUserGroupsResponseTests()
        {
            // TODO uncomment below to create an instance of ImportUserGroupsResponse
            //instance = new ImportUserGroupsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImportUserGroupsResponse
        /// </summary>
        [Fact]
        public void ImportUserGroupsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImportUserGroupsResponse
            //Assert.IsType<ImportUserGroupsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'GroupsAdded'
        /// </summary>
        [Fact]
        public void GroupsAddedTest()
        {
            // TODO unit test for the property 'GroupsAdded'
        }

        /// <summary>
        /// Test the property 'GroupsDeleted'
        /// </summary>
        [Fact]
        public void GroupsDeletedTest()
        {
            // TODO unit test for the property 'GroupsDeleted'
        }

        /// <summary>
        /// Test the property 'GroupsUpdated'
        /// </summary>
        [Fact]
        public void GroupsUpdatedTest()
        {
            // TODO unit test for the property 'GroupsUpdated'
        }
    }
}
