/*
 * ThoughtSpot Public REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ThoughtSpot.RestApi.Sdk.Model;
using ThoughtSpot.RestApi.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ThoughtSpot.RestApi.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookAuthOAuth2Input
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookAuthOAuth2InputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookAuthOAuth2Input
        //private WebhookAuthOAuth2Input instance;

        public WebhookAuthOAuth2InputTests()
        {
            // TODO uncomment below to create an instance of WebhookAuthOAuth2Input
            //instance = new WebhookAuthOAuth2Input();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookAuthOAuth2Input
        /// </summary>
        [Fact]
        public void WebhookAuthOAuth2InputInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookAuthOAuth2Input
            //Assert.IsType<WebhookAuthOAuth2Input>(instance);
        }

        /// <summary>
        /// Test the property 'AuthorizationUrl'
        /// </summary>
        [Fact]
        public void AuthorizationUrlTest()
        {
            // TODO unit test for the property 'AuthorizationUrl'
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Fact]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }
    }
}
