/*
 * ThoughtSpotPublicRESTAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost;

import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import localhost.controllers.AdminController;
import localhost.controllers.ConnectionController;
import localhost.controllers.CustomActionsController;
import localhost.controllers.DataController;
import localhost.controllers.DatabaseController;
import localhost.controllers.GroupController;
import localhost.controllers.LogsController;
import localhost.controllers.MaterializationController;
import localhost.controllers.MetadataController;
import localhost.controllers.OrgController;
import localhost.controllers.ReportController;
import localhost.controllers.SecurityController;
import localhost.controllers.SessionController;
import localhost.controllers.UserController;
import localhost.http.client.HttpCallback;
import localhost.http.client.HttpClientConfiguration;
import localhost.http.client.ReadonlyHttpClientConfiguration;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class ThoughtSpotPublicRESTAPIClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private UserController user;
    private GroupController group;
    private MetadataController metadata;
    private DatabaseController database;
    private ConnectionController connection;
    private DataController data;
    private LogsController logs;
    private CustomActionsController customActions;
    private SecurityController security;
    private OrgController org;
    private SessionController session;
    private AdminController admin;
    private ReportController report;
    private MaterializationController materialization;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "RestAPI V2 SDK";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * baseUrl value.
     */
    private final String baseUrl;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * BearerAuthManager.
     */
    private BearerAuthManager bearerAuthManager;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications;


    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private ThoughtSpotPublicRESTAPIClient(Environment environment, String baseUrl,
            HttpClient httpClient, ReadonlyHttpClientConfiguration httpClientConfig,
            String accessToken, Map<String, Authentication> authentications,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.baseUrl = baseUrl;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;
        this.authentications = 
                (authentications == null) ? new HashMap<>() : new HashMap<>(authentications);
        if (this.authentications.containsKey("global")) {
            this.bearerAuthManager = (BearerAuthManager) this.authentications.get("global");
        }

        if (!this.authentications.containsKey("global")
                || !getBearerAuthCredentials().equals(accessToken)) {
            this.bearerAuthManager = new BearerAuthManager(accessToken);
            this.authentications.put("global", bearerAuthManager);
        }

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .authentication(this.authentications).compatibilityFactory(compatibilityFactory)
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .callback(httpCallback)
                .userAgent(userAgent)
                .build();
        user = new UserController(globalConfig);
        group = new GroupController(globalConfig);
        metadata = new MetadataController(globalConfig);
        database = new DatabaseController(globalConfig);
        connection = new ConnectionController(globalConfig);
        data = new DataController(globalConfig);
        logs = new LogsController(globalConfig);
        customActions = new CustomActionsController(globalConfig);
        security = new SecurityController(globalConfig);
        org = new OrgController(globalConfig);
        session = new SessionController(globalConfig);
        admin = new AdminController(globalConfig);
        report = new ReportController(globalConfig);
        materialization = new MaterializationController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of UserController.
     * @return user
     */
    public UserController getUserController() {
        return user;
    }

    /**
     * Get the instance of GroupController.
     * @return group
     */
    public GroupController getGroupController() {
        return group;
    }

    /**
     * Get the instance of MetadataController.
     * @return metadata
     */
    public MetadataController getMetadataController() {
        return metadata;
    }

    /**
     * Get the instance of DatabaseController.
     * @return database
     */
    public DatabaseController getDatabaseController() {
        return database;
    }

    /**
     * Get the instance of ConnectionController.
     * @return connection
     */
    public ConnectionController getConnectionController() {
        return connection;
    }

    /**
     * Get the instance of DataController.
     * @return data
     */
    public DataController getDataController() {
        return data;
    }

    /**
     * Get the instance of LogsController.
     * @return logs
     */
    public LogsController getLogsController() {
        return logs;
    }

    /**
     * Get the instance of CustomActionsController.
     * @return customActions
     */
    public CustomActionsController getCustomActionsController() {
        return customActions;
    }

    /**
     * Get the instance of SecurityController.
     * @return security
     */
    public SecurityController getSecurityController() {
        return security;
    }

    /**
     * Get the instance of OrgController.
     * @return org
     */
    public OrgController getOrgController() {
        return org;
    }

    /**
     * Get the instance of SessionController.
     * @return session
     */
    public SessionController getSessionController() {
        return session;
    }

    /**
     * Get the instance of AdminController.
     * @return admin
     */
    public AdminController getAdminController() {
        return admin;
    }

    /**
     * Get the instance of ReportController.
     * @return report
     */
    public ReportController getReportController() {
        return report;
    }

    /**
     * Get the instance of MaterializationController.
     * @return materialization
     */
    public MaterializationController getMaterializationController() {
        return materialization;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * baseUrl value.
     * @return baseUrl
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with BearerAuth.
     * @return bearerAuthCredentials
     */
    private BearerAuthCredentials getBearerAuthCredentials() {
        return bearerAuthManager;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken
     */
    public String getAccessToken() {
        return getBearerAuthCredentials().getAccessToken();
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        parameters.put("base-url",
                new SimpleEntry<Object, Boolean>(this.baseUrl, false));
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "{base-url}";
            }
        }
        return "{base-url}";
    }

    /**
     * Converts this ThoughtSpotPublicRESTAPIClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ThoughtSpotPublicRESTAPIClient [" + "environment=" + environment + ", baseUrl="
                + baseUrl + ", httpClientConfig=" + httpClientConfig + ", authentications="
                + authentications + "]";
    }

    /**
     * Builds a new {@link ThoughtSpotPublicRESTAPIClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link ThoughtSpotPublicRESTAPIClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.baseUrl = getBaseUrl();
        builder.httpClient = getHttpClient();
        builder.accessToken = getBearerAuthCredentials().getAccessToken();
        builder.authentications = authentications;
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(configBldr -> configBldr =
                ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link ThoughtSpotPublicRESTAPIClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private String baseUrl = "https://localhost:443";
        private HttpClient httpClient;
        private String accessToken = "";
        private Map<String, Authentication> authentications = null;
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for BearerAuth.
         * @param accessToken String value for accessToken.
         * @return Builder
         */
        public Builder accessToken(String accessToken) {
            if (accessToken == null) {
                throw new NullPointerException("AccessToken cannot be null.");
            }
            this.accessToken = accessToken;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * baseUrl value.
         * @param baseUrl The baseUrl for client.
         * @return Builder
         */
        public Builder baseUrl(String baseUrl) {
            this.baseUrl = baseUrl;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Builds a new ThoughtSpotPublicRESTAPIClient object using the set fields.
         * @return ThoughtSpotPublicRESTAPIClient
         */
        public ThoughtSpotPublicRESTAPIClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new ThoughtSpotPublicRESTAPIClient(environment, baseUrl, httpClient,
                    httpClientConfig, accessToken, authentications, httpCallback);
        }
    }
}